name: Run CWD Data Workflow Daily at 6am PST (1pm UTC)

on:
  schedule:
    # Runs at 6am PST every day
    #- cron: '0 13 * * *'
    # Runs at 6am PST every day, Monday- Friday - for testing
    - cron: '0 13 * * MON-FRI'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    if: github.repository == 'emarmitage/nr-wildlife-health-cwd' # This ensures that only the ORIGINAL bcgov repo workflow is run
    runs-on: ubuntu-latest

    env:
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT}}
      S3_CWD_ACCESS_KEY: ${{ secrets.S3_CWD_ACCESS_KEY}}
      S3_CWD_SECRET_KEY: ${{ secrets.S3_CWD_SECRET_KEY}}
      AGO_TOKEN_URL: ${{ secrets.AGO_TOKEN_URL}}
      AGO_HOST: ${{ secrets.AGO_HOST}}
      AGO_ACCOUNT_ID: ${{ secrets.AGO_ACCOUNT_ID}}
      AGO_USERNAME: ${{ secrets.AGO_USERNAME}}
      AGO_PASSWORD: ${{ secrets.AGO_PASSWORD}}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python cwd_data_workflow_withAGO.py
