name: Run CWD scripts Twice Daily
on:
  schedule: 
    - cron: '0 11 * * MON-FRI'    # 11:00 AM UTC (3:00 AM PT)
    - cron: '15 20 * * MON-FRI'   # 20:15 PM UTC (12:15 PM PT)
  workflow_dispatch:
jobs:
  run-scripts:
    if: github.repository == 'bcgov/nr-wildlife-health-cwd' # This ensures that only the ORIGINAL bcgov repo workflow is run (not the forks!)
    runs-on: ubuntu-latest
    env:
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT}}
      S3_CWD_ACCESS_KEY: ${{ secrets.S3_CWD_ACCESS_KEY}}
      S3_CWD_SECRET_KEY: ${{ secrets.S3_CWD_SECRET_KEY}}
      AGO_TOKEN_URL: ${{ secrets.AGO_TOKEN_URL}}
      AGO_HOST: ${{ secrets.AGO_HOST}}
      AGO_ACCOUNT_ID: ${{ secrets.AGO_ACCOUNT_ID}}
      AGO_USERNAME: ${{ secrets.AGO_USERNAME}}
      AGO_PASSWORD: ${{ secrets.AGO_PASSWORD}}
      CHEFS_FORM_ID: ${{ secrets.CHEFS_FORM_ID}}
      CHEFS_API_KEY: ${{ secrets.CHEFS_API_KEY}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.19'
    - name: Install libkrb5 for Kerberos on Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y krb5-user libkrb5-dev
        #sudo apt-get install -y libkrb5-dev
        #pip install requests-kerberos
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run CWD Data Workflow
      run: python cwd_data_workflow.py
    - name: Run Update Dropoff Locations Layer
      run: python cwd_update_dropoff_locations_layer.py
